import ABIS from "../strategies/abis";

const BUSD_BSC = "0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56";
const USDC_BSC = "0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d";
const USDT_BSC = "0x55d398326f99059fF775485246999027B3197955";
const AAVE_MATIC = "0xd6df932a45c0f255f85145f286ea0b292b21c90b";
const WBTC_MATIC = "0x1bfd67037b42cf73acf2047067bd4f2c47d9bfd6";
const USDT_MATIC = "0xc2132D05D31c914a87C6611C10748AEb04B58e8F";
const USDC_MATIC = "0x2791bca1f2de4661ed88a30c99a7a9449aa84174";


const layer2Assets = [
	{
		name: "USDC",
		logo: "",
		tokenAddress: USDC_BSC,
		tokenAbi: ABIS.ERC20,
		protocolName: "xVault",
		protocolAddress: "",
		protocolAbi: ABIS.XVAULT,
		network: 56,
		decimals: 18,
		widthdrawDecimals: 36,
		ppfsMethod: 'pricePerShare',
	},
	{
		name: "USDT",
		logo: "",
		tokenAddress: USDT_BSC,
		tokenAbi: ABIS.ERC20,
		protocolName: "xVault",
		protocolAddress: "",
		protocolAbi: ABIS.XVAULT,
		network: 56,
		decimals: 18,
		widthdrawDecimals: 36,
		ppfsMethod: 'pricePerShare',
	},
	{
		name: "BUSD",
		logo: "",
		tokenAddress: BUSD_BSC,
		tokenAbi: ABIS.ERC20,
		protocolName: "xVault",
		protocolAddress: "",
		protocolAbi: ABIS.XVAULT,
		network: 56,
		decimals: 18,
		widthdrawDecimals: 36,
		ppfsMethod: 'pricePerShare',
	},

	{
		name: "BUSD",
		logo: "",
		tokenAddress: BUSD_BSC,
		tokenAbi: ABIS.BUSD,
		protocolName: "xAuto",
		protocolAddress: "",
		protocolAbi: ABIS.XAUTO,
		network: 56,
		decimals: 18,
		widthdrawDecimals: 36,
		ppfsMethod: 'getPricePerFullShare',
	},
	{
		name: "USDT",
		logo: "",
		tokenAddress: USDT_BSC,
		tokenAbi: ABIS.ERC20,
		protocolName: "xAuto",
		protocolAddress: "",
		protocolAbi: ABIS.XAUTO,
		network: 56,
		decimals: 18,
		widthdrawDecimals: 36,
		ppfsMethod: 'getPricePerFullShare',
	},
	{
		name: "BNB",
		logo: "",
		tokenAddress: "",
		tokenAbi: ABIS.ERC20,
		protocolName: "xAuto",
		protocolAddress: "",
		protocolAbi: ABIS.XAUTO,
		network: 56,
		decimals: 18,
		widthdrawDecimals: 36,
		ppfsMethod: 'getPricePerFullShare',
	},
	{
		name: "USDC",
		logo: "",
		tokenAddress: USDC_BSC,
		tokenAbi: ABIS.ERC20,
		protocolName: "xAuto",
		protocolAddress: "",
		protocolAbi: ABIS.XAUTO,
		network: 56,
		decimals: 18,
		widthdrawDecimals: 36,
		ppfsMethod: 'getPricePerFullShare',
	},


	{
		name: "USDC",
		logo: "",
		tokenAddress: USDC_MATIC,
		tokenAbi: ABIS.ERC20,
		protocolName: "xAuto",
		protocolAddress: "",
		protocolAbi: ABIS.XAUTO,
		network: 137,
		decimals: 18,
		widthdrawDecimals: 24,
		ppfsMethod: 'getPricePerFullShare',
	},
	{
		name: "USDT",
		logo: "",
		tokenAddress: USDT_MATIC,
		tokenAbi: ABIS.ERC20,
		protocolName: "xAuto",
		protocolAddress: "",
		protocolAbi: ABIS.XAUTO,
		network: 137,
		decimals: 18,
		widthdrawDecimals: 24,
		ppfsMethod: 'getPricePerFullShare',
	},
	{
		name: "AAVE",
		logo: "",
		tokenAddress: AAVE_MATIC,
		tokenAbi: ABIS.ERC20,
		protocolName: "xAuto",
		protocolAddress: "",
		protocolAbi: ABIS.XAUTO,
		network: 137,
		decimals: 18,
		widthdrawDecimals: 36,
		ppfsMethod: 'getPricePerFullShare',
	},
	{
		name: "WBTC",
		logo: "",
		tokenAddress: WBTC_MATIC,
		tokenAbi: ABIS.ERC20,
		protocolName: "xAuto",
		protocolAddress: "",
		protocolAbi: ABIS.XAUTO,
		network: 137,
		decimals: 18,
		widthdrawDecimals: 26,
		ppfsMethod: 'getPricePerFullShare',
	},
]

export default layer2Assets;